### ISSUE TITLE
some problem on computation of f1 score

### ISSUE THREAD

**Issue by jxyxiangyu** [slczgwh/REDN#13]
I have red your code about evaluation. When compute f1 score, you matmul the pred_result and gold matrix mask, then compute the mean for every relation. I can not see how you extract the entity, and may I understand this as relation classification but not relation extraction?

**Comment by slczgwh** [comment]
I think you mean joint-extraction? In joint-extraction, a full triplet like [h, t, rel]s is needed to be recognized, while in relation extraction, entities' messages are known as [h,t]s, and what we need to do is to recognize their [rel]s. Sometimes it also called relation classification, but I think it is only a defination problem.

**Comment by slczgwh** [comment]
I find an insteresting thing is that many people seem has similar question with you. Thus I can give you more details about what is the difference with joint-extraction and RE. Take a look at [GraphRel](https://www.aclweb.org/anthology/P19-1136.pdf), it claims itselfs as a joint-model of NER and RE: 

> In this paper, we propose GraphRel, a neural end-to-end joint model for entity recognition and relation extraction that is the first to handle allthree key aspects in relation extraction. 

An in [SpanBERT](https://arxiv.org/pdf/1907.10529.pdf), it show how they use RE dataset:
> Given one sentence and two spans within it – subject and object – the task is to predict the relation between the spans from 42 pre-defined relation types, including no_relation. We follow the entity masking schema from Zhang et al. (2017) and replace the subject and object entities by their NER tags such as “[CLS][SUBJ-PER] was born in [OBJ-LOC] , Michigan, . . . ”, and finally add a linear classifier on top of the [CLS]token to predict the relation type.
