### ISSUE TITLE
F1 on dataset semeval

### ISSUE THREAD

**Issue by zyccyz** [slczgwh/REDN#14]
In the master branch, the flag 'multi_label' is true on semeval. What's more, the calculation of f1  seems to ignore the case where the pred is positive, but the label is negative. I tried to solve these problems, and finally found that f1 could not reach the value in the paper.

**Comment by kemalaraz** [comment]
@zyccyz yeah same here on nyt10 dataset cannot reach papers results after 10 epoch as the paper suggested also tried till 100 epochs and still no luck.

**Comment by nannigath** [comment]
@kemalaraz  what was the score after 100 epoch?

**Comment by slczgwh** [comment]
This score evaluation method is from[ SemEval's Github](https://github.com/sahitya0000/Relation-Classification/blob/master/model/scorer_output.txt): it removes negative samples, which it called "excluded others".

**Comment by slczgwh** [comment]
NYT10's problem see [here](https://github.com/slczgwh/REDN/issues/12)
