### ISSUE TITLE
这是关系分类而不是关系抽取

### ISSUE THREAD

**Issue by sidney1994** [slczgwh/REDN#18]
这篇文章在测试的时候需要利用金标准的实体信息，而HBT这写关系抽取模型是预测实体和关系，这篇文章主要还是预测关系，假定实体给定，作者虽然在论文中提及了这个问题，但在结果比较中是不公平的，说自己的结果是SOTA也是不合理的。作者在文章中说自己的模型可以和NER结合，但代码中并没有体现这一点。

**Comment by sidney1994** [comment]
https://github.com/slczgwh/REDN/blob/156a33acfd6181d1367c1986120e16c974936164/opennre/framework/f1_metric.py#L48
https://github.com/slczgwh/REDN/blob/156a33acfd6181d1367c1986120e16c974936164/opennre/framework/f1_metric.py#L53
gold中完全没有实体的信息，只评价了关系label

**Comment by transformerzhou** [comment]
是的，应该根据预测矩阵来抽取实体，但是作者在代码里好像直接用了测试集的实体

**Comment by slczgwh** [comment]
统一回复在[这里](https://github.com/slczgwh/REDN/issues/21)
